// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzggeolcldvixweikosa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6Z2dlb2xjbGR2aXh3ZWlrb3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5Mzg1MTcsImV4cCI6MjA2MTUxNDUxN30.gBcOJixQpK1-rXnVRkAaKJdatIEpXSzBKO9o4q8-EdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);